name: nanny_core
description: A new Flutter package project.
publish_to: none
version: 0.0.1
#homepage:

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  crypto: ^3.0.3
  logger: ^2.0.2+1

  image_picker: ^1.0.4
  localstorage: ^4.0.1+4
  open_file_plus: ^3.4.1+1
  permission_handler: ^11.0.1

  local_auth: ^2.1.7
  local_auth_darwin: ^1.4.0

  intl: ^0.19.0
  http_parser: ^4.0.2
  web_socket_channel: ^2.4.0
  url_launcher: ^6.2.3
  path_provider: ^2.1.2

  location: ^5.0.3
  flutter_polyline_points:
    path: ./flutter_polyline_points
  google_maps_utils: ^2.0.0+1

  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.2
  app_links: ^4.0.0

  tinkoff_acquiring: ^3.0.10
  tinkoff_acquiring_flutter: ^3.0.10
  network_info_plus: ^3.0.5
  
  nanny_components:
    path: ../nanny_components

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
